[package]
name = "slatepack"
version = "0.1.0"
authors = ["j01tz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.3.0"
sha2 = "0.8.1"
